#This is an example of config files

[[Config]]
seed = 1234
generate_reference = 1
#*** if generate_reference == 1 ***#
path_reference = "./reference.fasta"

path_to_save_files = "./fileoutput/"
path_to_save_plot = "./Plot/"

Generate_graph = 1
#*** if Generate_graph == 0 ***#
Path_to_Graph = "./utility/Example_adj_matrix.txt"

Tree_Driver_Configure = 0
#*** if Tree_Driver == 1 ***#
edgelist_treedriver = "./utility/Tree_driver_example.txt"
driver_birth_rates = "./utility/driver_advantage.txt"
[[OutputGT]]
Tree_Newick = 1
Final_configuration = 1
Driver_list = 1
Driver_Tree = 1

[[FileOutputExperiments]]
Single_cell_fasta = 1
Single_cell_noise = 0
VAF_GT = 1
Bulk_noise = 1
Alignment = 1

[[FileOutputPlot]]
Time_of_sampling = [10, 20]
Graph_configuration = 1
